### ISSUE TITLE
Coneshell

### ISSUE THREAD

**Issue by krulci** [LukeFZ/DragaliaSaveDownloader#1]
How did you figured the coneshell for dragalia?
I am trying to do the same thing for PCRN and have been having hard time.
I was not able to attach a debugger to the game process nor calling coneshell.dll directly.

**Comment by krulci** [comment]
I got stuck at the step where the loginResponseData?.User == null
Failed to associate device with Nintendo account.

**Comment by LukeFZ** [comment]
Resolved externally.
