### ISSUE TITLE
Failed to get token

### ISSUE THREAD

**Issue by 123321mario** [LukeFZ/DragaliaSaveDownloader#2]
Login seems to work fine but as soon i choose my account i get this error and the cmd window closes...

![image](https://user-images.githubusercontent.com/33780173/214229030-617a0cff-92a8-4014-806b-e39f30c493ce.png)

**Comment by LukeFZ** [comment]
Which region is your Nintendo account in? Are you certain its the one you played Dragalia with?

I'm working on a build that prints the actual error, so I'll reply back once I have that finished

**Comment by 123321mario** [comment]
It's a japanese account I created for this game
I'll retry later on another PC

**Comment by 123321mario** [comment]
Okay well it's weird, on another PC on the same network as before it just works fine..?
Only difference I noticed is the first pc used cmd and the new used Windows Terminal

![image](https://user-images.githubusercontent.com/33780173/214240227-3964b192-0223-4738-84be-7e37c1b86aa2.png)

Ping me if you want me to retry with the new build on the first PC
